# Lab01 : Làm quen với Pytorch


### Bài 1. Tạo Tensor cơ bản

In [2]:
import torch
a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### Bài 2. Tạo các Tensor thường dùng

In [4]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)    

tensor([[0.1330, 0.1281, 0.9636, 0.4121],
        [0.6182, 0.1449, 0.4068, 0.6998],
        [0.7298, 0.9846, 0.7382, 0.8492]])
tensor([[-0.8442, -0.5748,  0.0114,  0.6116],
        [ 0.5103,  0.0914,  0.1767, -0.0692],
        [ 0.0932, -0.3577, -0.2137,  0.2057]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


### Yêu cầu của bài 2

In [5]:
import torch
f = torch.full((5, 5),10)

print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### Bài 3. Kiểm tra thông tin Tensor

In [6]:
import torch
a = torch.zeros(2, 3, 4)
print ("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### Bài 4. Slicing và Indexing

In [7]:
import torch
a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 0.4459, -0.8484,  0.2992,  2.4250, -0.2543],
         [ 0.0914,  0.7171,  0.7681, -0.5797,  0.1379],
         [ 0.7327,  2.1395,  0.6003,  1.2807, -0.5561],
         [-0.0674, -0.3624, -0.2162, -1.3842,  2.1359]],

        [[-1.4705, -0.2159,  0.1650,  2.5134,  0.0245],
         [-0.1468, -0.1969, -0.5095,  1.3433, -0.0788],
         [ 0.4599,  0.6126, -1.9693,  0.9687,  0.4310],
         [ 1.1686,  0.2999,  1.2864,  0.8863, -0.3955]],

        [[ 0.5270,  0.5403, -0.8067, -1.9371,  0.7906],
         [-0.4654,  0.4790, -0.2638, -0.0474, -0.2292],
         [ 0.6746, -0.3924, -0.3961, -0.7935,  0.1074],
         [-0.5368, -0.3334,  0.7713,  0.3309,  0.8935]]])

Tensor a[1]:
tensor([[-1.4705, -0.2159,  0.1650,  2.5134,  0.0245],
        [-0.1468, -0.1969, -0.5095,  1.3433, -0.0788],
        [ 0.4599,  0.6126, -1.9693,  0.9687,  0.4310],
        [ 1.1686,  0.2999,  1.2864,  0.8863, -0.3955]])

Tensor a[1:, 2:4]:
tensor([[[ 0.4599,  0.6126, -1.9693,  0.9687,  0.4

In [8]:
print("Hai phần tử cuối trên chiều thứ ba:")
print(a[:, :, -2:])

print("Shape:", a[:, :, -2:].shape)

Hai phần tử cuối trên chiều thứ ba:
tensor([[[ 2.4250, -0.2543],
         [-0.5797,  0.1379],
         [ 1.2807, -0.5561],
         [-1.3842,  2.1359]],

        [[ 2.5134,  0.0245],
         [ 1.3433, -0.0788],
         [ 0.9687,  0.4310],
         [ 0.8863, -0.3955]],

        [[-1.9371,  0.7906],
         [-0.0474, -0.2292],
         [-0.7935,  0.1074],
         [ 0.3309,  0.8935]]])
Shape: torch.Size([3, 4, 2])


### Bài 5. Reshape và Flatten

In [9]:
import torch
a = torch.randn(3, 4)

print("Original tensor:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original tensor:
tensor([[ 0.5669,  1.8174,  2.9944, -0.0445],
        [-1.0943,  0.5997, -1.2428, -0.7282],
        [ 0.5283,  0.6409,  0.2142, -0.3315]])

Flatten:
tensor([ 0.5669,  1.8174,  2.9944, -0.0445, -1.0943,  0.5997, -1.2428, -0.7282,
         0.5283,  0.6409,  0.2142, -0.3315])

Reshape to 3 x 2 x 2:
tensor([[[ 0.5669,  1.8174],
         [ 2.9944, -0.0445]],

        [[-1.0943,  0.5997],
         [-1.2428, -0.7282]],

        [[ 0.5283,  0.6409],
         [ 0.2142, -0.3315]]])


In [10]:
print("Số phần tử trước reshape:", a.numel())

b = a.reshape(3, 2, 2)

print("Số phần tử sau reshape:", b.numel())

Số phần tử trước reshape: 12
Số phần tử sau reshape: 12


In [11]:
c = a.reshape(2, 6)

print("Reshape thành 2 x 6:")
print(c)

print("Shape:", c.shape)
print("Số phần tử:", c.numel())

Reshape thành 2 x 6:
tensor([[ 0.5669,  1.8174,  2.9944, -0.0445, -1.0943,  0.5997],
        [-1.2428, -0.7282,  0.5283,  0.6409,  0.2142, -0.3315]])
Shape: torch.Size([2, 6])
Số phần tử: 12


### Bài 6. Phép toán và nhân ma trận

In [13]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 0.3614, -1.5948, -0.7121],
        [ 1.1145, -0.1245,  0.2897]])
b:
tensor([[-0.5972,  0.9582, -0.7782],
        [-0.5344, -0.2258,  0.2166]])

a + b:
tensor([[-0.2358, -0.6366, -1.4903],
        [ 0.5801, -0.3503,  0.5063]])

a / b:
tensor([[-0.6051, -1.6644,  0.9151],
        [-2.0857,  0.5513,  1.3373]])

a^2:
tensor([[0.1306, 2.5433, 0.5071],
        [1.2421, 0.0155, 0.0839]])

Matrix multiplication:
tensor([[-1.1897,  0.0128],
        [-1.0103, -0.5047]])


In [16]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("\nMatrix multiplication:")
print("a @ b.T:", (a @ b.T).shape)


Matrix multiplication:
a @ b.T: torch.Size([2, 2])


### Bài 7. Các hàm thống kê trên Tensor

In [17]:
import torch
a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=0))

print("\nStandard deviation:")
print(torch.std(a, dim=0))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.5128, -1.5745,  0.3662, -1.1115],
        [ 1.3441, -0.8410,  1.2763, -0.8010],
        [ 0.6731, -0.0123, -1.2679, -0.5389]])

Mean:
tensor([ 0.8433, -0.8093,  0.1249, -0.8171])

Standard deviation:
tensor([0.4410, 0.7816, 1.2891, 0.2866])

Cumulative sum:
tensor([[ 0.5128, -1.5745,  0.3662, -1.1115],
        [ 1.8570, -2.4155,  1.6425, -1.9125],
        [ 2.5300, -2.4278,  0.3746, -2.4514]])


In [18]:
import torch
a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=1))

print("\nStandard deviation:")
print(torch.std(a, dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[-0.3683, -0.1142,  0.7528,  0.5404],
        [ 1.1739, -1.4672, -1.3892, -1.1178],
        [-0.6931, -1.6233,  1.8238, -1.0875]])

Mean:
tensor([ 0.2027, -0.7001, -0.3950])

Standard deviation:
tensor([0.5301, 1.2582, 1.5275])

Cumulative sum:
tensor([[-0.3683, -0.4825,  0.2703,  0.8107],
        [ 1.1739, -0.2933, -1.6824, -2.8002],
        [-0.6931, -2.3164, -0.4926, -1.5802]])


### Bài 8. Autograd cơ bản

In [19]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [20]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = 3*x**2 + 2*x +1

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


### Bài 9. Gradient Descent tìm hệ số đa thức

In [21]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
    
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.4539],
        [-0.0542],
        [ 0.0496]], requires_grad=True)
Learned coefficients:
tensor([[1.0179],
        [2.0383],
        [2.0578]], requires_grad=True)


### Bài 10. Giải hệ phương trình bằng Autograd

In [23]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.4661, requires_grad=True)
B = tensor(4.5338, requires_grad=True)
C = tensor(3.5339, requires_grad=True)
D = tensor(2.5338, requires_grad=True)


### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau

In [25]:
import torch
a = torch.randn(2, 3, 4)

print("Tensor:")
print(a)

print("\nReshape to 4 x 6:")
print(a.reshape(4, 6))

print("\nReshape to 2 x 12:")
print(a.reshape(2, 12))

print("\nReshape to 2 x 3 x 4:")
print(a.reshape(2, 3, 4))


Tensor:
tensor([[[ 1.1077, -0.5385,  0.3986,  2.2109],
         [ 1.5802, -1.0879, -0.1009, -1.0660],
         [-0.0227,  1.1182, -0.4917, -0.4492]],

        [[ 0.1489,  0.0868, -1.3377,  1.4796],
         [-1.7506,  0.6041, -0.5895, -0.8905],
         [ 0.1458,  1.0882, -0.5769,  0.2255]]])

Reshape to 4 x 6:
tensor([[ 1.1077, -0.5385,  0.3986,  2.2109,  1.5802, -1.0879],
        [-0.1009, -1.0660, -0.0227,  1.1182, -0.4917, -0.4492],
        [ 0.1489,  0.0868, -1.3377,  1.4796, -1.7506,  0.6041],
        [-0.5895, -0.8905,  0.1458,  1.0882, -0.5769,  0.2255]])

Reshape to 2 x 12:
tensor([[ 1.1077, -0.5385,  0.3986,  2.2109,  1.5802, -1.0879, -0.1009, -1.0660,
         -0.0227,  1.1182, -0.4917, -0.4492],
        [ 0.1489,  0.0868, -1.3377,  1.4796, -1.7506,  0.6041, -0.5895, -0.8905,
          0.1458,  1.0882, -0.5769,  0.2255]])

Reshape to 2 x 3 x 4:
tensor([[[ 1.1077, -0.5385,  0.3986,  2.2109],
         [ 1.5802, -1.0879, -0.1009, -1.0660],
         [-0.0227,  1.1182, -0.4917, -

In [37]:
import torch

a = torch.randn(3, 4)
b = torch.randn(3, 4)

print(a)
print(b)
print("\na + b:")
print(a + b)
print("\na * b:")
print(a * b)
print("\na / b:")
print(a / b)
print("Mean a:")
print(torch.mean(a, dim=0))
print("Mean b:")
print(torch.mean(b, dim=0))
print("Std a:")
print(torch.std(a, dim=0))
print("Std b:")
print(torch.std(b, dim=0))

tensor([[ 1.2788, -0.3493, -1.6491,  0.9205],
        [ 0.6703, -0.0207,  1.8173, -1.3813],
        [ 0.4734,  0.9048,  1.0057,  0.4796]])
tensor([[ 0.3124,  0.3769, -2.0006,  0.7965],
        [-1.2402,  0.7834, -1.1996,  0.7026],
        [-1.4417, -0.1379, -0.0898,  0.9997]])

a + b:
tensor([[ 1.5913,  0.0276, -3.6497,  1.7169],
        [-0.5699,  0.7627,  0.6177, -0.6786],
        [-0.9683,  0.7669,  0.9159,  1.4793]])

a * b:
tensor([[ 0.3996, -0.1317,  3.2992,  0.7331],
        [-0.8313, -0.0162, -2.1800, -0.9705],
        [-0.6826, -0.1247, -0.0904,  0.4794]])

a / b:
tensor([[  4.0930,  -0.9267,   0.8243,   1.1557],
        [ -0.5405,  -0.0265,  -1.5150,  -1.9658],
        [ -0.3284,  -6.5627, -11.1952,   0.4797]])
Mean a:
tensor([0.8075, 0.1782, 0.3913, 0.0063])
Mean b:
tensor([-0.7898,  0.3408, -1.0967,  0.8329])
Std a:
tensor([0.4199, 0.6503, 1.8130, 1.2217])
Std b:
tensor([0.9599, 0.4617, 0.9595, 0.1518])


In [41]:
import torch

x = torch.tensor(
    2.0,
    requires_grad=True
)

y = 2 * x * x + 5 * x + 3

y.backward()

print("x =", x)
print("y =", y)
print("dy/dx =", x.grad)

x = tensor(2., requires_grad=True)
y = tensor(21., grad_fn=<AddBackward0>)
dy/dx = tensor(13.)


In [43]:
import numpy as np
import torch

polynomial = np.poly1d([2, -3, 5])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(5000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
    
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.5195],
        [ 1.2652],
        [-0.8209]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0001],
        [-3.0001],
        [ 4.9960]], requires_grad=True)
