# Lab01 : Làm quen với Pytorch


### Bài 1. Tạo Tensor cơ bản

In [3]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### Bài 2. Tạo các Tensor thường dùng

In [4]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)    

tensor([[0.1146, 0.6633, 0.5972, 0.5430],
        [0.3695, 0.5358, 0.3672, 0.5962],
        [0.0272, 0.9162, 0.8282, 0.5637]])
tensor([[ 0.0816, -0.0716, -0.5481,  0.1367],
        [ 0.3270,  0.8099, -0.6769, -1.0263],
        [-0.1510, -1.3971,  0.5753, -0.6251]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


### Yêu cầu của bài 2

In [5]:
import torch
f = torch.full((5, 5),10)

print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### Bài 3. Kiểm tra thông tin Tensor

In [6]:
import torch
a = torch.zeros(2, 3, 4)
print ("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### Bài 4. Slicing và Indexing

In [7]:
import torch
a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 1.6823,  0.0261,  0.6499,  1.3668, -1.2198],
         [ 0.5344, -1.9512, -1.4393, -0.6662,  0.6483],
         [-0.3157, -0.2053,  0.9060, -0.3238, -1.2500],
         [-0.8963, -0.0779,  0.9828, -0.7557, -0.2881]],

        [[ 0.2700,  0.8985,  0.3639, -1.0454,  1.4189],
         [-0.5946, -1.1419, -0.3538, -0.4880,  2.3049],
         [-0.0935, -1.7701, -0.8518,  1.1067, -1.2099],
         [-0.0287,  0.9031, -1.7937,  0.7062, -0.1816]],

        [[ 0.5630,  0.0705,  0.6467, -0.4504,  0.7367],
         [ 1.2626,  0.2996, -1.1200, -1.4662, -1.5094],
         [ 1.0587, -0.3015,  2.1358,  0.0779,  0.5222],
         [-0.1521,  1.4495, -0.4791,  0.9077,  0.6898]]])

Tensor a[1]:
tensor([[ 0.2700,  0.8985,  0.3639, -1.0454,  1.4189],
        [-0.5946, -1.1419, -0.3538, -0.4880,  2.3049],
        [-0.0935, -1.7701, -0.8518,  1.1067, -1.2099],
        [-0.0287,  0.9031, -1.7937,  0.7062, -0.1816]])

Tensor a[1:, 2:4]:
tensor([[[-0.0935, -1.7701, -0.8518,  1.1067, -1.2

In [8]:
print("Hai phần tử cuối trên chiều thứ ba:")
print(a[:, :, -2:])

print("Shape:", a[:, :, -2:].shape)

Hai phần tử cuối trên chiều thứ ba:
tensor([[[ 1.3668, -1.2198],
         [-0.6662,  0.6483],
         [-0.3238, -1.2500],
         [-0.7557, -0.2881]],

        [[-1.0454,  1.4189],
         [-0.4880,  2.3049],
         [ 1.1067, -1.2099],
         [ 0.7062, -0.1816]],

        [[-0.4504,  0.7367],
         [-1.4662, -1.5094],
         [ 0.0779,  0.5222],
         [ 0.9077,  0.6898]]])
Shape: torch.Size([3, 4, 2])


### Bài 5. Reshape và Flatten

In [9]:
import torch
a = torch.randn(3, 4)

print("Original tensor:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original tensor:
tensor([[-1.0943, -1.6914,  0.2369,  0.7621],
        [ 1.3736, -0.2130,  0.8384,  0.3224],
        [-0.1756, -1.0690,  0.4859,  0.3277]])

Flatten:
tensor([-1.0943, -1.6914,  0.2369,  0.7621,  1.3736, -0.2130,  0.8384,  0.3224,
        -0.1756, -1.0690,  0.4859,  0.3277])

Reshape to 3 x 2 x 2:
tensor([[[-1.0943, -1.6914],
         [ 0.2369,  0.7621]],

        [[ 1.3736, -0.2130],
         [ 0.8384,  0.3224]],

        [[-0.1756, -1.0690],
         [ 0.4859,  0.3277]]])


In [10]:
print("Số phần tử trước reshape:", a.numel())

b = a.reshape(3, 2, 2)

print("Số phần tử sau reshape:", b.numel())

Số phần tử trước reshape: 12
Số phần tử sau reshape: 12


In [11]:
c = a.reshape(2, 6)

print("Reshape thành 2 x 6:")
print(c)

print("Shape:", c.shape)
print("Số phần tử:", c.numel())

Reshape thành 2 x 6:
tensor([[-1.0943, -1.6914,  0.2369,  0.7621,  1.3736, -0.2130],
        [ 0.8384,  0.3224, -0.1756, -1.0690,  0.4859,  0.3277]])
Shape: torch.Size([2, 6])
Số phần tử: 12


### Bài 6. Phép toán và nhân ma trận

In [12]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-1.0525, -1.1153,  0.9140],
        [-0.2499,  0.0183,  0.0779]])
b:
tensor([[ 0.1231, -0.5196,  0.8211],
        [ 0.1432, -0.1409,  0.2323]])

a + b:
tensor([[-0.9294, -1.6349,  1.7351],
        [-0.1067, -0.1226,  0.3101]])

a / b:
tensor([[-8.5489,  2.1466,  1.1131],
        [-1.7449, -0.1300,  0.3353]])

a^2:
tensor([[1.1078e+00, 1.2440e+00, 8.3541e-01],
        [6.2464e-02, 3.3535e-04, 6.0654e-03]])

Matrix multiplication:
tensor([[ 1.2004,  0.2187],
        [ 0.0237, -0.0203]])


In [13]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("\nMatrix multiplication:")
print("a @ b.T:", (a @ b.T).shape)


Matrix multiplication:
a @ b.T: torch.Size([2, 2])


### Bài 7. Các hàm thống kê trên Tensor

In [14]:
import torch
a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=0))

print("\nStandard deviation:")
print(torch.std(a, dim=0))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.6056, -0.3142,  0.8234,  0.9466],
        [-0.8106, -2.6630,  0.2636,  0.5822],
        [ 1.3540, -0.2275, -0.1290,  0.2167]])

Mean:
tensor([-0.0207, -1.0683,  0.3193,  0.5819])

Standard deviation:
tensor([1.1950, 1.3818, 0.4787, 0.3650])

Cumulative sum:
tensor([[-0.6056, -0.3142,  0.8234,  0.9466],
        [-1.4163, -2.9773,  1.0870,  1.5289],
        [-0.0622, -3.2048,  0.9580,  1.7456]])


In [15]:
import torch
a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=1))

print("\nStandard deviation:")
print(torch.std(a, dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[-1.5266,  0.4021, -0.3380, -1.6664],
        [ 1.2571,  0.5451,  0.2984, -0.8617],
        [ 0.7430, -1.7249,  0.8397,  0.9007]])

Mean:
tensor([-0.7822,  0.3097,  0.1896])

Standard deviation:
tensor([0.9893, 0.8804, 1.2780])

Cumulative sum:
tensor([[-1.5266, -1.1244, -1.4624, -3.1288],
        [ 1.2571,  1.8022,  2.1006,  1.2389],
        [ 0.7430, -0.9819, -0.1422,  0.7585]])


### Bài 8. Autograd cơ bản

In [16]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [17]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = 3*x**2 + 2*x +1

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


### Bài 9. Gradient Descent tìm hệ số đa thức

In [18]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
    
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.3508],
        [ 1.2019],
        [-1.4893]], requires_grad=True)
Learned coefficients:
tensor([[1.0388],
        [1.8858],
        [1.1462]], requires_grad=True)


### Bài 10. Giải hệ phương trình bằng Autograd

In [19]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.2403, requires_grad=True)
B = tensor(4.7597, requires_grad=True)
C = tensor(3.7597, requires_grad=True)
D = tensor(2.7597, requires_grad=True)


### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau

In [20]:
import torch
a = torch.randn(2, 3, 4)

print("Tensor:")
print(a)

print("\nReshape to 4 x 6:")
print(a.reshape(4, 6))

print("\nReshape to 2 x 12:")
print(a.reshape(2, 12))

print("\nReshape to 2 x 3 x 4:")
print(a.reshape(2, 3, 4))


Tensor:
tensor([[[-1.3222,  1.0009,  1.0166,  0.6195],
         [ 1.4323, -0.0362, -0.5510,  0.4208],
         [ 1.9357, -0.6315,  0.3862, -0.6957]],

        [[ 0.1616,  0.5731,  2.2534, -0.2300],
         [ 0.1705,  1.0691, -1.3165, -0.6808],
         [-0.0370,  0.8820, -0.6077,  0.6539]]])

Reshape to 4 x 6:
tensor([[-1.3222,  1.0009,  1.0166,  0.6195,  1.4323, -0.0362],
        [-0.5510,  0.4208,  1.9357, -0.6315,  0.3862, -0.6957],
        [ 0.1616,  0.5731,  2.2534, -0.2300,  0.1705,  1.0691],
        [-1.3165, -0.6808, -0.0370,  0.8820, -0.6077,  0.6539]])

Reshape to 2 x 12:
tensor([[-1.3222,  1.0009,  1.0166,  0.6195,  1.4323, -0.0362, -0.5510,  0.4208,
          1.9357, -0.6315,  0.3862, -0.6957],
        [ 0.1616,  0.5731,  2.2534, -0.2300,  0.1705,  1.0691, -1.3165, -0.6808,
         -0.0370,  0.8820, -0.6077,  0.6539]])

Reshape to 2 x 3 x 4:
tensor([[[-1.3222,  1.0009,  1.0166,  0.6195],
         [ 1.4323, -0.0362, -0.5510,  0.4208],
         [ 1.9357, -0.6315,  0.3862, -

In [21]:
import torch

a = torch.randn(3, 4)
b = torch.randn(3, 4)

print(a)
print(b)
print("\na + b:")
print(a + b)
print("\na * b:")
print(a * b)
print("\na / b:")
print(a / b)
print("Mean a:")
print(torch.mean(a, dim=0))
print("Mean b:")
print(torch.mean(b, dim=0))
print("Std a:")
print(torch.std(a, dim=0))
print("Std b:")
print(torch.std(b, dim=0))

tensor([[ 0.7305, -1.0327,  0.3005, -2.1394],
        [-1.6708, -0.6220, -0.5384, -1.5228],
        [-0.6246, -0.0053, -0.0456,  1.2853]])
tensor([[ 0.0626, -0.1523, -0.6147, -1.5960],
        [-0.9286,  0.8639, -0.1749, -0.0230],
        [ 0.5229, -0.6307, -0.3421, -0.5042]])

a + b:
tensor([[ 0.7931, -1.1850, -0.3142, -3.7354],
        [-2.5994,  0.2419, -0.7133, -1.5458],
        [-0.1017, -0.6361, -0.3876,  0.7811]])

a * b:
tensor([[ 4.5732e-02,  1.5726e-01, -1.8473e-01,  3.4146e+00],
        [ 1.5515e+00, -5.3738e-01,  9.4179e-02,  3.4984e-02],
        [-3.2662e-01,  3.3711e-03,  1.5588e-02, -6.4811e-01]])

a / b:
tensor([[ 1.1669e+01,  6.7816e+00, -4.8884e-01,  1.3405e+00],
        [ 1.7993e+00, -7.1999e-01,  3.0776e+00,  6.6286e+01],
        [-1.1945e+00,  8.4740e-03,  1.3323e-01, -2.5490e+00]])
Mean a:
tensor([-0.5216, -0.5534, -0.0945, -0.7923])
Mean b:
tensor([-0.1144,  0.0270, -0.3772, -0.7077])
Std a:
tensor([1.2040, 0.5171, 0.4216, 1.8255])
Std b:
tensor([0.7417, 0.7633, 

In [22]:
import torch

x = torch.tensor(
    2.0,
    requires_grad=True
)

y = 2 * x * x + 5 * x + 3

y.backward()

print("x =", x)
print("y =", y)
print("dy/dx =", x.grad)

x = tensor(2., requires_grad=True)
y = tensor(21., grad_fn=<AddBackward0>)
dy/dx = tensor(13.)


In [23]:
import numpy as np
import torch

polynomial = np.poly1d([2, -3, 5])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(5000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
    
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.4482],
        [ 0.2587],
        [ 0.2135]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0000],
        [-3.0000],
        [ 4.9994]], requires_grad=True)
