# Lab01 : Làm quen với Pytorch


### Bài 1. Tạo Tensor cơ bản

In [1]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### Bài 2. Tạo các Tensor thường dùng

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)    

tensor([[0.2719, 0.4016, 0.2080, 0.4648],
        [0.2535, 0.6771, 0.0084, 0.7024],
        [0.8329, 0.5613, 0.1956, 0.4877]])
tensor([[-0.0544,  0.0140, -0.1264, -0.1702],
        [ 0.8922, -1.1774, -0.0677, -2.5447],
        [-0.2704, -2.1063,  0.9178, -0.7902]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


### Yêu cầu của bài 2

In [3]:
import torch
f = torch.full((5, 5),10)

print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### Bài 3. Kiểm tra thông tin Tensor

In [4]:
import torch
a = torch.zeros(2, 3, 4)
print ("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### Bài 4. Slicing và Indexing

In [5]:
import torch
a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 0.9163, -0.2290, -0.6506, -0.3796, -0.0359],
         [-0.8594,  1.7057, -0.3486, -0.3848, -0.6676],
         [-0.6777, -0.8504, -0.5172,  0.3309, -0.1934],
         [ 0.4507, -0.2343,  1.3169, -0.3486,  0.0721]],

        [[ 2.3876,  0.8636,  0.8703,  0.2114,  0.1558],
         [ 1.5549, -0.3071, -0.5172,  0.7733, -0.1198],
         [ 1.2842, -0.2763, -2.6530,  0.3172, -0.6766],
         [-2.2028,  0.0795,  0.1600,  2.0199, -1.0467]],

        [[-0.3136, -0.4070,  1.0369, -0.0280,  0.2528],
         [ 0.4436, -1.1008, -1.7361, -0.5165, -0.9960],
         [ 0.6753,  0.5259,  0.1842,  0.3967, -1.3918],
         [-0.6860,  0.9620, -1.0659, -1.7358, -0.8356]]])

Tensor a[1]:
tensor([[ 2.3876,  0.8636,  0.8703,  0.2114,  0.1558],
        [ 1.5549, -0.3071, -0.5172,  0.7733, -0.1198],
        [ 1.2842, -0.2763, -2.6530,  0.3172, -0.6766],
        [-2.2028,  0.0795,  0.1600,  2.0199, -1.0467]])

Tensor a[1:, 2:4]:
tensor([[[ 1.2842, -0.2763, -2.6530,  0.3172, -0.6

In [6]:
print("Hai phần tử cuối trên chiều thứ ba:")
print(a[:, :, -2:])

print("Shape:", a[:, :, -2:].shape)

Hai phần tử cuối trên chiều thứ ba:
tensor([[[-0.3796, -0.0359],
         [-0.3848, -0.6676],
         [ 0.3309, -0.1934],
         [-0.3486,  0.0721]],

        [[ 0.2114,  0.1558],
         [ 0.7733, -0.1198],
         [ 0.3172, -0.6766],
         [ 2.0199, -1.0467]],

        [[-0.0280,  0.2528],
         [-0.5165, -0.9960],
         [ 0.3967, -1.3918],
         [-1.7358, -0.8356]]])
Shape: torch.Size([3, 4, 2])


### Bài 5. Reshape và Flatten

In [7]:
import torch
a = torch.randn(3, 4)

print("Original tensor:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original tensor:
tensor([[-0.1582,  0.7558, -1.1925, -1.1088],
        [ 0.8052,  0.2536,  1.0917,  1.6105],
        [-0.7876,  0.6154,  0.8550, -0.2712]])

Flatten:
tensor([-0.1582,  0.7558, -1.1925, -1.1088,  0.8052,  0.2536,  1.0917,  1.6105,
        -0.7876,  0.6154,  0.8550, -0.2712])

Reshape to 3 x 2 x 2:
tensor([[[-0.1582,  0.7558],
         [-1.1925, -1.1088]],

        [[ 0.8052,  0.2536],
         [ 1.0917,  1.6105]],

        [[-0.7876,  0.6154],
         [ 0.8550, -0.2712]]])


In [8]:
print("Số phần tử trước reshape:", a.numel())

b = a.reshape(3, 2, 2)

print("Số phần tử sau reshape:", b.numel())

Số phần tử trước reshape: 12
Số phần tử sau reshape: 12


In [9]:
c = a.reshape(2, 6)

print("Reshape thành 2 x 6:")
print(c)

print("Shape:", c.shape)
print("Số phần tử:", c.numel())

Reshape thành 2 x 6:
tensor([[-0.1582,  0.7558, -1.1925, -1.1088,  0.8052,  0.2536],
        [ 1.0917,  1.6105, -0.7876,  0.6154,  0.8550, -0.2712]])
Shape: torch.Size([2, 6])
Số phần tử: 12


### Bài 6. Phép toán và nhân ma trận

In [10]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 1.0883, -1.4426,  0.8597],
        [ 0.0935, -1.3204,  1.1283]])
b:
tensor([[ 2.1888,  0.2984, -0.9791],
        [-1.2522,  0.0399, -0.5532]])

a + b:
tensor([[ 3.2771, -1.1442, -0.1195],
        [-1.1587, -1.2804,  0.5751]])

a / b:
tensor([[  0.4972,  -4.8346,  -0.8780],
        [ -0.0747, -33.0784,  -2.0397]])

a^2:
tensor([[1.1844, 2.0812, 0.7391],
        [0.0087, 1.7433, 1.2731]])

Matrix multiplication:
tensor([[ 1.1098, -1.8959],
        [-1.2942, -0.7939]])


In [11]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("\nMatrix multiplication:")
print("a @ b.T:", (a @ b.T).shape)


Matrix multiplication:
a @ b.T: torch.Size([2, 2])


### Bài 7. Các hàm thống kê trên Tensor

In [12]:
import torch
a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=0))

print("\nStandard deviation:")
print(torch.std(a, dim=0))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.5521, -1.1500, -0.6548,  0.2483],
        [-1.0391, -0.9768, -0.6070,  0.4151],
        [ 1.4462, -0.4534,  1.0290, -1.3513]])

Mean:
tensor([-0.0484, -0.8601, -0.0776, -0.2293])

Standard deviation:
tensor([1.3170, 0.3627, 0.9586, 0.9752])

Cumulative sum:
tensor([[-0.5521, -1.1500, -0.6548,  0.2483],
        [-1.5912, -2.1268, -1.2618,  0.6634],
        [-0.1451, -2.5802, -0.2329, -0.6879]])


In [13]:
import torch
a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=1))

print("\nStandard deviation:")
print(torch.std(a, dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.7673,  0.8724,  2.1521,  1.1696],
        [-1.3303, -1.1103,  1.1441,  0.0035],
        [ 0.5939,  0.0252,  0.3781, -0.3079]])

Mean:
tensor([ 1.2403, -0.3232,  0.1723])

Standard deviation:
tensor([0.6312, 1.1392, 0.3968])

Cumulative sum:
tensor([[ 0.7673,  1.6397,  3.7917,  4.9614],
        [-1.3303, -2.4405, -1.2965, -1.2930],
        [ 0.5939,  0.6191,  0.9971,  0.6892]])


### Bài 8. Autograd cơ bản

In [14]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [15]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = 3*x**2 + 2*x +1

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


### Bài 9. Gradient Descent tìm hệ số đa thức

In [16]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
    
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.7269],
        [-0.3880],
        [-0.2703]], requires_grad=True)
Learned coefficients:
tensor([[1.0118],
        [2.0131],
        [2.1977]], requires_grad=True)


### Bài 10. Giải hệ phương trình bằng Autograd

In [17]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.6201, requires_grad=True)
B = tensor(4.3798, requires_grad=True)
C = tensor(3.3799, requires_grad=True)
D = tensor(2.3799, requires_grad=True)


### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau

In [18]:
import torch
a = torch.randn(2, 3, 4)

print("Tensor:")
print(a)

print("\nReshape to 4 x 6:")
print(a.reshape(4, 6))

print("\nReshape to 2 x 12:")
print(a.reshape(2, 12))

print("\nReshape to 2 x 3 x 4:")
print(a.reshape(2, 3, 4))


Tensor:
tensor([[[-0.5253,  0.5863, -1.0349,  0.7121],
         [-0.9898,  2.1849,  0.8440,  0.0058],
         [ 0.7739, -0.3203,  0.0227, -0.1400]],

        [[ 0.0683,  0.9640,  0.0843, -0.4039],
         [-0.1553,  0.4551, -1.4622, -2.0721],
         [-1.1084,  2.3302,  0.0600,  0.9881]]])

Reshape to 4 x 6:
tensor([[-0.5253,  0.5863, -1.0349,  0.7121, -0.9898,  2.1849],
        [ 0.8440,  0.0058,  0.7739, -0.3203,  0.0227, -0.1400],
        [ 0.0683,  0.9640,  0.0843, -0.4039, -0.1553,  0.4551],
        [-1.4622, -2.0721, -1.1084,  2.3302,  0.0600,  0.9881]])

Reshape to 2 x 12:
tensor([[-0.5253,  0.5863, -1.0349,  0.7121, -0.9898,  2.1849,  0.8440,  0.0058,
          0.7739, -0.3203,  0.0227, -0.1400],
        [ 0.0683,  0.9640,  0.0843, -0.4039, -0.1553,  0.4551, -1.4622, -2.0721,
         -1.1084,  2.3302,  0.0600,  0.9881]])

Reshape to 2 x 3 x 4:
tensor([[[-0.5253,  0.5863, -1.0349,  0.7121],
         [-0.9898,  2.1849,  0.8440,  0.0058],
         [ 0.7739, -0.3203,  0.0227, -

In [19]:
import torch

a = torch.randn(3, 4)
b = torch.randn(3, 4)

print(a)
print(b)
print("\na + b:")
print(a + b)
print("\na * b:")
print(a * b)
print("\na / b:")
print(a / b)
print("Mean a:")
print(torch.mean(a, dim=0))
print("Mean b:")
print(torch.mean(b, dim=0))
print("Std a:")
print(torch.std(a, dim=0))
print("Std b:")
print(torch.std(b, dim=0))

tensor([[ 1.0295,  1.2852,  2.7687, -0.9206],
        [-0.2796,  1.7452,  0.5913,  1.4902],
        [-0.3018, -0.0083, -0.6575,  0.4011]])
tensor([[ 0.2403,  0.1575, -0.2607, -1.0576],
        [-0.9924,  0.0125,  1.7980, -0.5974],
        [ 1.4857, -1.1138, -1.7710, -0.0859]])

a + b:
tensor([[ 1.2697,  1.4427,  2.5080, -1.9783],
        [-1.2720,  1.7577,  2.3894,  0.8928],
        [ 1.1839, -1.1221, -2.4285,  0.3152]])

a * b:
tensor([[ 0.2474,  0.2024, -0.7219,  0.9737],
        [ 0.2774,  0.0218,  1.0632, -0.8903],
        [-0.4484,  0.0092,  1.1644, -0.0345]])

a / b:
tensor([[ 4.2845e+00,  8.1602e+00, -1.0619e+01,  8.7050e-01],
        [ 2.8171e-01,  1.3974e+02,  3.2888e-01, -2.4943e+00],
        [-2.0315e-01,  7.4075e-03,  3.7127e-01, -4.6698e+00]])
Mean a:
tensor([0.1494, 1.0074, 0.9008, 0.3236])
Mean b:
tensor([ 0.2445, -0.3146, -0.0779, -0.5803])
Std a:
tensor([0.7623, 0.9091, 1.7340, 1.2073])
Std b:
tensor([1.2390, 0.6959, 1.7915, 0.4861])


In [20]:
import torch

x = torch.tensor(
    2.0,
    requires_grad=True
)

y = 2 * x * x + 5 * x + 3

y.backward()

print("x =", x)
print("y =", y)
print("dy/dx =", x.grad)

x = tensor(2., requires_grad=True)
y = tensor(21., grad_fn=<AddBackward0>)
dy/dx = tensor(13.)


In [21]:
import numpy as np
import torch

polynomial = np.poly1d([2, -3, 5])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(5000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
    
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.7599],
        [ 0.2523],
        [-0.8743]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0006],
        [-3.0017],
        [ 4.9455]], requires_grad=True)
